name: Go
on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go:
          - "1.13"
          - "1.14"
          - "1.15"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go }}"
      - run: make test
      - uses: codecov/codecov-action@v1
